version: "3"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - 3000:3000
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend/:/code/
      - ~/.config/gcloud:/root/.config/gcloud
    ports:
      - 5050:5050
